apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend-job-adda
  labels:
    app: django-backend-job-adda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend-job-adda
  template:
    metadata:
      labels:
        app: django-backend-job-adda
    spec:
      containers:
      - name: django-job-adda-kube
        imagePullPolicy: Always
        image: gopalghule05/lnx_job_adda_argocd:3
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
