apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend-job-adda
  labels:
    app: django-backend-job-adda
  namespace: job-portal
spec:
  replicas: 5
  selector:
    matchLabels:
      app: django-backend-job-adda
  template:
    metadata:
      labels:
        app: django-backend-job-adda
    spec:
      containers:
      - name: django-job-adda-kube
        imagePullPolicy: Always
        image: gopalghule05/lnx_job_adda_argocd:6
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5
