apiVersion: v1
kind: Service
metadata:
  name: django-backend-job-adda-service
spec:
  selector:
    app: django-backend-job-adda
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8000
  type: NodePort
